backend:
  name: github
  repo: mwickett/forbes-web # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "team" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Team" # Used in the UI, ie.: "New Post"
    folder: "_collections/team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name", name: "name", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
